sudo: false
language: scala
scala:
- 2.10.5
- 2.11.6
jdk:
- oraclejdk7
script:
- sbt -Dfile.encoding=UTF8 -no-colors ++$TRAVIS_SCALA_VERSION test
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
notifications:
  slack:
    secure: NOpL1XMu0iZPfMyfNU+TzWjUnxCcvc/9wAt4gj2FxSdfvC6j3Ww9cUthBttBLWwDN/bAKhC2F+PdTssavno1zYLG3ZkdyrsLhCgjgpHtXESzi2QCUD1nILv5MLBu8qaMlDuZym7ZGWPF0rFInaXHccxMicX2usCBeR5YDwJRunc=
